modLoader = "lowcodefml"
loaderVersion="[40,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://discord.lunareclipse.studio/"
showAsResourcePack = false

[[mods]]
modId="demon_eyes"
version="1.2"
displayName="Eyes In The Sky"
credits="§8Created by §5☆Lunar Eclipse Studios☆"
displayURL="https://lunareclipse.studio/creations/eyes-in-the-sky"
logoFile="banner.png"
authors="Bret06"
description='''Eyes In The Sky is a small Minecraft datapack that adds demon eyes from the game Terraria!'''

[[dependencies.demon_eyes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.2,1.21.4]"
    ordering="NONE"
    side="BOTH"



